"""Tests for envguard.templater."""

from pathlib import Path

import pytest

from envguard.templater import (
    PlaceholderStyle,
    TemplateResult,
    generate_template,
    write_template,
)


SAMPLE_ENV = {"DATABASE_URL": "postgres://localhost/db", "SECRET_KEY": "s3cr3t", "DEBUG": "true"}


def test_keys_are_sorted():
    result = generate_template(SAMPLE_ENV)
    assert result.keys == ["DATABASE_URL", "DEBUG", "SECRET_KEY"]


def test_key_count():
    result = generate_template(SAMPLE_ENV)
    assert result.key_count == 3


def test_angle_style_placeholder():
    result = generate_template({"API_KEY": "real"}, style=PlaceholderStyle.ANGLE)
    assert "API_KEY=<YOUR_API_KEY>" in result.output


def test_empty_style_placeholder():
    result = generate_template({"API_KEY": "real"}, style=PlaceholderStyle.EMPTY)
    assert "API_KEY=" in result.output
    assert "<" not in result.output


def test_describe_style_placeholder():
    result = generate_template({"DB_HOST": "localhost"}, style=PlaceholderStyle.DESCRIBE)
    assert "DB_HOST=<DESCRIBE_db-host>" in result.output


def test_default_header_present():
    result = generate_template(SAMPLE_ENV)
    assert result.output.startswith("# Auto-generated by envguard")


def test_custom_header():
    result = generate_template(SAMPLE_ENV, header="# my custom header")
    assert result.output.startswith("# my custom header")


def test_no_header():
    result = generate_template({"FOO": "bar"}, header=None)
    assert result.output.startswith("FOO=")


def test_empty_env_returns_only_header():
    result = generate_template({}, header="# header")
    assert result.key_count == 0
    assert "# header" in result.output


def test_output_ends_with_newline():
    result = generate_template(SAMPLE_ENV)
    assert result.output.endswith("\n")


def test_write_template_creates_file(tmp_path: Path):
    dest = tmp_path / ".env.example"
    result = write_template(SAMPLE_ENV, dest)
    assert dest.exists()
    content = dest.read_text()
    assert content == result.output


def test_write_template_returns_result(tmp_path: Path):
    dest = tmp_path / ".env.example"
    result = write_template({"PORT": "8080"}, dest, style=PlaceholderStyle.EMPTY)
    assert isinstance(result, TemplateResult)
    assert result.keys == ["PORT"]
