"""Generate .env.example template files from existing .env files."""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from pathlib import Path
from typing import Dict, List


class PlaceholderStyle(str, Enum):
    EMPTY = "empty"          # KEY=
    ANGLE = "angle"          # KEY=<YOUR_KEY>
    DESCRIBE = "describe"    # KEY=<DESCRIBE_KEY>


@dataclass
class TemplateResult:
    keys: List[str] = field(default_factory=list)
    output: str = ""

    @property
    def key_count(self) -> int:
        return len(self.keys)


def _placeholder(key: str, style: PlaceholderStyle) -> str:
    """Return the placeholder value for a given key and style."""
    if style == PlaceholderStyle.EMPTY:
        return ""
    if style == PlaceholderStyle.ANGLE:
        return f"<YOUR_{key}>"
    if style == PlaceholderStyle.DESCRIBE:
        return f"<DESCRIBE_{key.lower().replace('_', '-')}>"
    return ""


def generate_template(
    env: Dict[str, str],
    style: PlaceholderStyle = PlaceholderStyle.ANGLE,
    header: str | None = "# Auto-generated by envguard — do not commit real values",
) -> TemplateResult:
    """Generate a .env.example template from a parsed env dict."""
    lines: List[str] = []
    if header:
        lines.append(header)
        lines.append("")

    sorted_keys = sorted(env.keys())
    for key in sorted_keys:
        placeholder = _placeholder(key, style)
        lines.append(f"{key}={placeholder}")

    output = "\n".join(lines)
    if lines:
        output += "\n"

    return TemplateResult(keys=sorted_keys, output=output)


def write_template(
    env: Dict[str, str],
    dest: Path,
    style: PlaceholderStyle = PlaceholderStyle.ANGLE,
    header: str | None = "# Auto-generated by envguard — do not commit real values",
) -> TemplateResult:
    """Generate and write a template file to *dest*."""
    result = generate_template(env, style=style, header=header)
    dest.write_text(result.output, encoding="utf-8")
    return result
